title:              rychlovláďa.cz
email:              
description:        Rychloopravna obuvi, výroba klíčů, obuvnické, ortopedické a brašnářské práce
author:             Máca a Vláďa
baseurl:            "/rychlovlada"
url:                "https://jiri001meitner.github.io/rychlovlada/"
creator_name:       Jiří Meitner
creator_linkedin:   "https://www.linkedin.com/in/meitner/"
creator_web:        "https://itislove.cz"
creator_web_name:   ITisLove.cz
creator_web_moto:   IT služby s láskou

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-382375003 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# exclude:
#  - "_posts/*"
