name: IndexNow notify on publish

on:
  workflow_run:
    workflows: ["Deploy Jekyll to GitHub Pages"]
    types:
      - completed

jobs:
  indexnow:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Extract changed URLs
        id: extract_changed_urls
        run: |
          echo "Collecting changed URLs..."
          git fetch origin main
          URLS=$(git diff --name-only FETCH_HEAD HEAD | grep -E '\\.(md|html)$' || true)
          echo "Changed files: $URLS"
          FINAL_URLS=""
          if [ -n "$URLS" ]; then
            while IFS= read -r file; do
              [ -z "$file" ] && continue
              if [[ "$file" == _posts/* ]]; then
                url=$(echo "$file" | sed -E 's#^_posts/([0-9]{4})-([0-9]{2})-([0-9]{2})-(.*)\\.(md|html)#https://rychlovlada.cz/\\1/\\2/\\3/\\4.html#')
                FINAL_URLS="$FINAL_URLS$url\\n"
              else
                clean_path=$(echo "$file" | sed -E 's#\\.md$#.html#')
                url="https://rychlovlada.cz/$clean_path"
                FINAL_URLS="$FINAL_URLS$url\\n"
              fi
            done <<< "$URLS"
          fi
          echo -e "Prepared URLs for IndexNow:\n$FINAL_URLS"
          echo "URL_LIST<<EOF" >> $GITHUB_ENV
          echo -e "$FINAL_URLS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Extract all URLs from sitemap if no changes detected
        if: env.URL_LIST == ''
        run: |
          echo "No changed files detected, falling back to sitemap."
          FINAL_URLS=$(curl -s https://rychlovlada.cz/sitemap.xml | grep -oP '(?<=<loc>)[^<]+' | grep '^https://rychlovlada.cz' || true)
          echo -e "Prepared URLs for IndexNow (from sitemap):\n$FINAL_URLS"
          echo "URL_LIST<<EOF" >> $GITHUB_ENV
          echo -e "$FINAL_URLS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Notify IndexNow
        if: env.URL_LIST != ''
        run: |
          INDEXNOW_KEY="5d8b838ff8a8410eebcfe2105c9f4c5d"
          JSON_BODY=$(printf '{"host":"rychlovlada.cz","key":"%s","urlList":[%s]}' "$INDEXNOW_KEY" "$(echo "$URL_LIST" | sed 's/^/\"/;s/$/\",/' | tr -d '\n' | sed 's/,$//')")
          echo "Sending payload: $JSON_BODY"
          curl -H "Content-Type: application/json" -d "$JSON_BODY" "https://api.indexnow.org/indexnow"
