name: IndexNow notify on publish

on:
  push:
    branches:
      - main

jobs:
  indexnow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract changed URLs
        id: extract_urls
        run: |
          echo "Collecting changed URLs..."
          URLS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^_posts/' | sed 's/^/_site\//;s/\\.md$/\\.html/' | awk '{print "https://rychlovlada.cz/"$0}')
          echo "URL_LIST<<EOF" >> $GITHUB_ENV
          echo "$URLS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Notify IndexNow
        if: env.URL_LIST != ''
        env:
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
        run: |
          JSON_BODY=$(printf '{"host":"rychlovlada.cz","key":"%s","urlList":[%s]}' "$INDEXNOW_KEY" "$(echo \"$URL_LIST\" | sed 's/^/\"/;s/$/\",/' | tr -d '\\n' | sed 's/,$//')")
          echo "Sending payload: $JSON_BODY"
          curl -H "Content-Type: application/json" -d "$JSON_BODY" "https://api.indexnow.org/indexnow"

