name: IndexNow notify on publish

on:
  push:
    branches:
      - main

jobs:
  indexnow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history to prevent 'bad object' errors

      - name: Extract changed URLs
        id: extract_urls
        run: |
          echo "Collecting changed URLs..."
          URLS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} 2>/dev/null || git ls-files '_posts/*')
          URLS=$(echo "$URLS" | grep '^_posts/' | grep -E '\\.(md|html)$' | sed 's/^/_site\//;s/\\.md$/.html/;s/\\.html$/.html/' | awk '{print "https://rychlovlada.cz/"$0}')
          echo "URL_LIST<<EOF" >> $GITHUB_ENV
          echo "$URLS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Notify IndexNow
        if: env.URL_LIST != ''
        run: |
          INDEXNOW_KEY="5d8b838ff8a8410eebcfe2105c9f4c5d"
          JSON_BODY=$(printf '{"host":"rychlovlada.cz","key":"%s","urlList":[%s]}' "$INDEXNOW_KEY" "$(echo "$URL_LIST" | sed 's/^/\"/;s/$/\",/' | tr -d '\\n' | sed 's/,$//')")
          echo "Sending payload: $JSON_BODY"
          curl -H "Content-Type: application/json" -d "$JSON_BODY" "https://api.indexnow.org/indexnow"
