name: IndexNow notify on publish

on:
  push:
    branches:
      - main

jobs:
  indexnow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract changed URLs
        id: extract_urls
        run: |
          echo "Collecting changed URLs..."
          URLS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} || true)
          echo "Raw changed files:" "$URLS"
          if [ -z "$URLS" ]; then
            if [ -f "_site/sitemap.xml" ]; then
              echo "Using sitemap.xml fallback"
              URLS=$(xmllint --xpath '//*[local-name()="url"]/*[local-name()="loc"]/text()' _site/sitemap.xml | tr '\n' '\n')
              echo "Loaded URLs from sitemap:" "$URLS"
            else
              URLS=$(git ls-files '_posts/*')
              echo "Using all files fallback:" "$URLS"
            fi
          fi
          FILTERED=$(echo "$URLS" | grep '^_posts/' | grep -E '\\.(md|html)$' || true)
          echo "Filtered post files:" "$FILTERED"
          URLS=$(echo "$FILTERED" | sed -E 's#^_posts/([0-9]{4})-([0-9]{2})-([0-9]{2})-(.*)\\.md#\1/\2/\3/\4.html#;s#^_posts/([0-9]{4})-([0-9]{2})-([0-9]{2})-(.*)\\.html#\1/\2/\3/\4.html#' | awk '{print "https://rychlovlada.cz/"$0}')
          echo "Prepared URLs for IndexNow:" "$URLS"
          echo "URL_LIST<<EOF" >> $GITHUB_ENV
          echo "$URLS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Notify IndexNow
        if: env.URL_LIST != ''
        run: |
          INDEXNOW_KEY="5d8b838ff8a8410eebcfe2105c9f4c5d"
          JSON_BODY=$(printf '{"host":"rychlovlada.cz","key":"%s","urlList":[%s]}' "$INDEXNOW_KEY" "$(echo "$URL_LIST" | sed 's/^/\"/;s/$/\",/' | tr -d '\n' | sed 's/,$//')")
          echo "Sending payload: $JSON_BODY"
          curl -H "Content-Type: application/json" -d "$JSON_BODY" "https://api.indexnow.org/indexnow"
