name: IndexNow notify on publish

on:
  push:
    branches:
      - main

jobs:
  indexnow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract URLs from sitemap
        id: extract_urls
        run: |
          echo "Collecting URLs from sitemap..."
          if [ -f "_site/sitemap.xml" ]; then
            URLS=$(xmllint --xpath '//*[local-name()="url"]/*[local-name()="loc"]/text()' _site/sitemap.xml | grep '^https://rychlovlada.cz' || true)
            echo "Loaded URLs from sitemap:" "$URLS"
          else
            echo "No sitemap found, skipping IndexNow notification."
            URLS=""
          fi
          echo "Prepared URLs for IndexNow:" "$URLS"
          echo "URL_LIST<<EOF" >> $GITHUB_ENV
          echo "$URLS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Notify IndexNow
        if: env.URL_LIST != ''
        run: |
          INDEXNOW_KEY="5d8b838ff8a8410eebcfe2105c9f4c5d"
          JSON_BODY=$(printf '{"host":"rychlovlada.cz","key":"%s","urlList":[%s]}' "$INDEXNOW_KEY" "$(echo "$URL_LIST" | sed 's/^/\"/;s/$/\",/' | tr -d '\n' | sed 's/,$//')")
          echo "Sending payload: $JSON_BODY"
          curl -H "Content-Type: application/json" -d "$JSON_BODY" "https://api.indexnow.org/indexnow"
