name: IndexNow notify on publish

on:
  workflow_run:
    workflows: ["jekyll-gh-pages"]
    types:
      - completed
    branches:
      - main

jobs:
  indexnow:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Extract URLs from live sitemap
        id: extract_urls
        run: |
          echo "Collecting URLs from live sitemap..."
          URLS=$(curl -s https://rychlovlada.cz/sitemap.xml | grep -oP '(?<=<loc>)[^<]+' | grep '^https://rychlovlada.cz' || true)
          echo "Loaded URLs from live sitemap:" "$URLS"
          echo "Prepared URLs for IndexNow:" "$URLS"
          echo "URL_LIST<<EOF" >> $GITHUB_ENV
          echo "$URLS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Notify IndexNow
        if: env.URL_LIST != ''
        run: |
          INDEXNOW_KEY="5d8b838ff8a8410eebcfe2105c9f4c5d"
          JSON_BODY=$(printf '{"host":"rychlovlada.cz","key":"%s","urlList":[%s]}' "$INDEXNOW_KEY" "$(echo "$URL_LIST" | sed 's/^/\"/;s/$/\",/' | tr -d '\n' | sed 's/,$//')")
          echo "Sending payload: $JSON_BODY"
          curl -H "Content-Type: application/json" -d "$JSON_BODY" "https://api.indexnow.org/indexnow"
